using Gallop;
using LibMMD.Material;
using LibMMD.Model;
using LibMMD.Reader;
using LibMMD.Unity3D;
using LibMMD.Writer;
using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEngine.Rendering;
using Gallop.Live.Cutt; // For FacialMouthId
using static BillboardBuilder;
using static LibMMD.Model.Morph;
using static LibMMD.Model.SkinningOperator;
//using UnityGLTF;


public class ModelExporter
{
    static string modelInfo = $"Generated by UmaViewer {Application.version}, Copyright Cygames \nLink : https://github.com/katboi01/UmaViewer";

    public static void ExportModel(UmaContainerCharacter container, string path)
    {
        PMXExportStateSnapshot stateSnapshot = new PMXExportStateSnapshot(container);
        try 
        {
            stateSnapshot.FreezeForExport();
            // PMX 与 VMD 共用同一套 MMD 默认 A-pose，避免导出当前动画帧或近似 T-pose。
            stateSnapshot.ApplyMmdReferencePose();
            container.FaceDrivenKeyTarget?.FacialResetAll();
            AddBlendShape(container);
            BuildBillboard(container);

            var textures = TextureExporter.ExportAllTexture(Path.GetDirectoryName(path), container.gameObject);
            var model = ReadPMXModel(container, textures, container.CharaEntry);

            using (FileStream fileStream = new FileStream(path, FileMode.Create))
            using (BinaryWriter writer = new BinaryWriter(fileStream))
            {
                var config = new ModelConfig() { GlobalToonPath = "Toon" };
                PMXWriter.Write(writer, model, config);
            }
        }
        finally
        {
            try
            {
                RemoveBillboard(container);
                ClearBlendShape(container);
            }
            finally
            {
                // 临时导出资源清理失败时，也必须恢复角色的姿势和运行时组件。
                stateSnapshot.Dispose();
            }
        }

        UmaViewerUI.Instance.ShowMessage($"PMX Save at {path}", UIMessageType.Success);
    }

    public static void ExportModel(UmaContainer container, string path)
    {

        var textures = TextureExporter.ExportAllTexture(Path.GetDirectoryName(path), container.gameObject);
        var model = ReadPMXModel(container, textures);

        FileStream fileStream = new FileStream(path, FileMode.Create);
        BinaryWriter writer = new BinaryWriter(fileStream);
        var config = new ModelConfig() { GlobalToonPath = "Toon" };
        PMXWriter.Write(writer, model, config);

        writer.Close();
        fileStream.Close();

        UmaViewerUI.Instance.ShowMessage($"PMX Save at {path}", UIMessageType.Success);
    }

    public static RawMMDModel ReadPMXModel(UmaContainer container, string[] textures, CharaEntry entry = null)
    {
        RawMMDModel model = new RawMMDModel();
        if (entry != null)
        {
            model.Name = entry.Name;
            model.NameEn = entry.GetName();
            model.Description = model.DescriptionEn = $"{entry.GetName()}\n{modelInfo}";
        }
        else
        {
            model.Name = container.gameObject.name;
            model.NameEn = container.gameObject.name;
            model.Description = model.DescriptionEn = $"{container.gameObject.name}\n{modelInfo}";
        }

        // 仅从蒙皮引用收集骨骼，避免把 Handle、Pole、Target 等运行时控制节点导出为 PMX 骨骼。
        var rootBone = container.transform.Find("Position");
        if (rootBone == null)
        {
            rootBone = container.transform;
        }
        List<Renderer> renderers = new List<Renderer>(container.GetComponentsInChildren<Renderer>());
        PMXBoneExporter.Result boneResult = PMXBoneExporter.Build(rootBone, container.transform, renderers);

        //Read vertices And triangles
        List<int> triangles = new List<int>();
        model.Vertices = ReadVerticesAndTriangles(renderers, boneResult.BoneIndexes, ref triangles, container.transform);
        model.TriangleIndexes = triangles.ToArray();

        //Read Texture reference
        foreach (var texture in textures)
        {
            model.TextureList.Add(new MMDTexture(texture));
        }

        model.Parts = ReadPartMaterials(renderers, model);
        model.Bones = boneResult.Bones;
        if(container is UmaContainerCharacter chara)
        {
            ClearBlendShape(chara);
            AddBlendShape(chara);
        }
        model.Morphs = ReadMorph(renderers);
        model.Rigidbodies = new MMDRigidBody[0];
        model.Joints = new MMDJoint[0];

        return model;
    }

    public static Vector3[] Vec4ToVec3(Vector4[] vector4s)
    {
        Vector3[] tmp = new Vector3[vector4s.Length];
        for (int i = 0; i < vector4s.Length; i++)
        {
            tmp[i] = new Vector3(vector4s[i].x, vector4s[i].y, vector4s[i].z);
        }
        return tmp;
    }

    public static Vector3[] CalDelta(Vector3[] ori, Vector3[] end)
    {
        Vector3[] tmp = new Vector3[ori.Length];
        for (int i = 0; i < ori.Length; i++)
        {
            tmp[i] = end[i] - ori[i];
        }
        return tmp;
    }

    private static void AddBlendShape(UmaContainerCharacter container)
    {
        if (!container.FaceDrivenKeyTarget) return;
        SkinnedMeshRenderer faceMesh = null;
        SkinnedMeshRenderer eyebrowMesh = null;
        SkinnedMeshRenderer earMesh = null;
        SkinnedMeshRenderer mouthMesh = null; // New
        SkinnedMeshRenderer eyeMesh = null;   // New

        foreach (SkinnedMeshRenderer s in container.GetComponentsInChildren<SkinnedMeshRenderer>())
        {
            if (s.name.Equals("M_Face")) faceMesh = s;
            else if (s.name.Equals("M_Mayu")) eyebrowMesh = s;
            else if (s.name.Equals("M_Hair")) earMesh = s;
            else if (s.name.Equals("M_Mouth")) mouthMesh = s; // New
            else if (s.name.Equals("M_Eye")) eyeMesh = s;     // New
        }

        var facial = container.FaceDrivenKeyTarget;
        Action<SkinnedMeshRenderer, List<FacialMorph>, Mesh> addBlendShapePart = delegate (SkinnedMeshRenderer skin, List<FacialMorph> morphs, Mesh baseMesh)
        {
            container.FaceOverrideData = null;
            foreach (var morph in morphs)
            {
                facial.ClearAllWeights();
                // [Fix] Reset weight to 1 (User request: 10x was too strong)
                morph.weight = 1; 
                facial.ChangeMorph();

                Mesh deltaMesh = new Mesh();
                skin.BakeMesh(deltaMesh);

            // [Fix] Truncate name to 15 bytes (Shift-JIS) to match VMD limit
            string validName = TruncateToShiftJIS(morph.name, 15);

            // [Fix] Check duplicate using truncated name
            if (skin.sharedMesh.GetBlendShapeIndex(validName) == -1)
            {
                // [Fix] Use weight 100.0f (Standard Unity Full Weight)
                // Previous value 1.0f meant "This delta is for 1% weight", causing MMD (100%) to explode the mesh 100x.
                skin.sharedMesh.AddBlendShapeFrame(validName, 100.0f,
                    CalDelta(baseMesh.vertices, deltaMesh.vertices),
                    CalDelta(baseMesh.normals, deltaMesh.normals),
                    CalDelta(Vec4ToVec3(baseMesh.tangents), Vec4ToVec3(deltaMesh.tangents)));
                }
            }
        };

        if (faceMesh)
        {
            Mesh basefaceMesh = new Mesh();
            faceMesh.BakeMesh(basefaceMesh);
            addBlendShapePart(faceMesh, facial.EyeBrowMorphs, basefaceMesh);
            addBlendShapePart(faceMesh, facial.EyeMorphs, basefaceMesh);
            addBlendShapePart(faceMesh, facial.MouthMorphs, basefaceMesh);
        }
        
        if (eyebrowMesh)
        {
            Mesh baseEyeBrowMesh = new Mesh();
            eyebrowMesh.BakeMesh(baseEyeBrowMesh);
            addBlendShapePart(eyebrowMesh, facial.EyeBrowMorphs, baseEyeBrowMesh);
        }

        if (earMesh)
        {
            Mesh baseEarMesh = new Mesh();
            earMesh.BakeMesh(baseEarMesh);
            addBlendShapePart(earMesh, facial.EarMorphs, baseEarMesh);
        }

        // [New] Process Mouth Mesh
        if (mouthMesh)
        {
            Mesh baseMouthMesh = new Mesh();
            mouthMesh.BakeMesh(baseMouthMesh);
            addBlendShapePart(mouthMesh, facial.MouthMorphs, baseMouthMesh);
        }

        // [New] Process Eye Mesh
        if (eyeMesh)
        {
            Mesh baseEyeMesh = new Mesh();
            eyeMesh.BakeMesh(baseEyeMesh);
            addBlendShapePart(eyeMesh, facial.EyeMorphs, baseEyeMesh);
        }
            
        facial.ClearAllWeights();
        facial.ChangeMorph();
    }

    private static void ClearBlendShape(UmaContainerCharacter container)
    {
        if (!container.FaceDrivenKeyTarget) return;
        //assuming base meshes do not have any blend shapes
        foreach (SkinnedMeshRenderer s in container.GetComponentsInChildren<SkinnedMeshRenderer>())
        {
            if (s.name.Equals("M_Face") || s.name.Equals("M_Mayu") || s.name.Equals("M_Hair") ||
                s.name.Equals("M_Mouth") || s.name.Equals("M_Eye"))
            {
                s.sharedMesh.ClearBlendShapes();
            }
        }
    }

    private static string TruncateToShiftJIS(string s, int maxBytes)
    {
        var encoding = System.Text.Encoding.GetEncoding("shift_jis");
        byte[] bytes = encoding.GetBytes(s);
        if (bytes.Length <= maxBytes) return s;
        return encoding.GetString(bytes, 0, maxBytes);
    }

    private static Morph[] ReadMorph(List<Renderer> renderers)
    {
        Dictionary<string, List<VertexMorphData>> mergedMorphData = new Dictionary<string, List<VertexMorphData>>();
        int vertexOffset = 0;

        foreach (Renderer renderer in renderers)
        {
            Mesh mesh;
            if (renderer is MeshRenderer mr)
            {
                var meshfilter = mr.GetComponent<MeshFilter>();
                mesh = meshfilter.mesh;
            }
            else
            {
                mesh = ((SkinnedMeshRenderer)renderer).sharedMesh;
            }
            var vertexCount = mesh.vertexCount;

            for (int i = 0; i < mesh.blendShapeCount; i++)
            {
                string morphName = mesh.GetBlendShapeName(i);
                
                if (!mergedMorphData.ContainsKey(morphName))
                {
                    mergedMorphData[morphName] = new List<VertexMorphData>();
                }

                var deltaVertices = new Vector3[vertexCount];
                var deltaNormals = new Vector3[vertexCount];
                var deltaTangents = new Vector3[vertexCount];
                mesh.GetBlendShapeFrameVertices(i, 0, deltaVertices, deltaNormals, deltaTangents);

                for (int j = 0; j < vertexCount; j++)
                {
                    // Optimization: Only include vertices that actually move
                    if (deltaVertices[j].sqrMagnitude > 0.000001f)
                    {
                        var data = new VertexMorphData();
                        data.VertexIndex = vertexOffset + j;
                        data.Offset = deltaVertices[j];
                        mergedMorphData[morphName].Add(data);
                    }
                }
            }
            vertexOffset += vertexCount;
        }

        List<Morph> finalMorphs = new List<Morph>();

        // Accumulator for MMD Mapped Morphs (e.g. "まばたき" will collect vertices from "Eye_L" and "Eye_R")
        Dictionary<string, List<VertexMorphData>> mmdMorphData = new Dictionary<string, List<VertexMorphData>>();

        foreach (var kvp in mergedMorphData)
        {
            string rawName = kvp.Key;

            // 1. Create Unity Original Morph (Always keep original)
            Morph morph = CreateMorph(rawName, rawName, kvp.Value);
            finalMorphs.Add(morph);

            // 2. Check for Mapping to MMD
            string mmdName = GetMappedMMDName(rawName);
            if (!string.IsNullOrEmpty(mmdName))
            {
                if (!mmdMorphData.ContainsKey(mmdName))
                {
                    mmdMorphData[mmdName] = new List<VertexMorphData>();
                }
                // Merge vertices (Union of deltas)
                mmdMorphData[mmdName].AddRange(kvp.Value);
            }
        }

        // 3. Create MMD Mapped Morphs
        foreach (var kvp in mmdMorphData)
        {
            Morph mmdMorph = CreateMorph(kvp.Key, kvp.Key, kvp.Value);
            finalMorphs.Add(mmdMorph);
        }

        return finalMorphs.ToArray();
    }

    private static Morph CreateMorph(string name, string nameEn, List<VertexMorphData> datas)
    {
        Morph morph = new Morph();
        morph.Name = name;
        morph.NameEn = nameEn;
        morph.Type = MorphType.MorphTypeVertex;
        morph.MorphDatas = datas.ToArray();

        // Categorize based on Name content (Simple heuristic)
        if (morph.NameEn.Contains("Mouth") || morph.Name.Contains("口") || morph.NameEn.Contains("Lip"))
        {
            morph.Category = MorphCategory.MorphCatMouth;
        }
        else if (morph.NameEn.Contains("EyeBrow") || morph.Name.Contains("眉"))
        {
            morph.Category = MorphCategory.MorphCatEyebrow;
        }
        else if (morph.NameEn.Contains("Eye") || morph.Name.Contains("目") || morph.Name.Contains("まばたき"))
        {
            morph.Category = MorphCategory.MorphCatEye;
        }
        else
        {
            morph.Category = MorphCategory.MorphCatOther;
        }
        return morph;
    }

    private static string GetMappedMMDName(string rawName)
    {
        // 1. Direct Mapping
        if (MorphNameMapping.TryGetValue(rawName, out string mapped)) return mapped;

        // 2. Parse Unity Patterns (e.g. Eye_2_L -> Eye_CloseA -> まばたき)
        
        // Eyes: Eye_{id}_{L/R}
        if (rawName.StartsWith("Eye_"))
        {
             var parts = rawName.Split('_');
             if (parts.Length >= 2 && int.TryParse(parts[1], out int id))
             {
                 if (Enum.IsDefined(typeof(Gallop.Live.Cutt.LiveTimelineDefine.FacialEyeId), id))
                 {
                     string tag = Enum.GetName(typeof(Gallop.Live.Cutt.LiveTimelineDefine.FacialEyeId), id);
                     string key = "Eye_" + tag; // e.g. "Eye_CloseA"
                     if (MorphNameMapping.TryGetValue(key, out string mmdName)) return mmdName;
                 }
             }
        }
        // Eyebrows: EyeBrow_{id}_{L/R}
        else if (rawName.StartsWith("EyeBrow_"))
        {
             var parts = rawName.Split('_');
             if (parts.Length >= 2 && int.TryParse(parts[1], out int id))
             {
                 if (Enum.IsDefined(typeof(Gallop.Live.Cutt.LiveTimelineDefine.FacialEyebrowId), id))
                 {
                     string tag = Enum.GetName(typeof(Gallop.Live.Cutt.LiveTimelineDefine.FacialEyebrowId), id);
                     string key = "EyeBrow_" + tag;
                     if (MorphNameMapping.TryGetValue(key, out string mmdName)) return mmdName;
                 }
             }
        }
        // Mouth: Mouth_{id}_{index}
        else if (rawName.StartsWith("Mouth_"))
        {
             var parts = rawName.Split('_');
             if (parts.Length >= 2 && int.TryParse(parts[1], out int id))
             {
                 if (Enum.IsDefined(typeof(Gallop.Live.Cutt.LiveTimelineDefine.FacialMouthId), id))
                 {
                     string tag = Enum.GetName(typeof(Gallop.Live.Cutt.LiveTimelineDefine.FacialMouthId), id);
                     string key = "Mouth_" + tag; // e.g. "Mouth_WaraiA"
                     
                     if (MorphNameMapping.TryGetValue(key, out string mmdName)) return mmdName;
                     
                     // Fallback for Mouth which sometimes had "Mouth" prefix in mapping keys or direct names?
                     // Existing mapping has keys like "Mouth_WaraiA". So "Mouth_" + tag is correct.
                     
                     // Check for specialized suffix matches if needed, but for now tag matching is safer
                 }
             }
        }

        return null;
    }

    // UmaViewer Morph Name -> MMD Standard Name Mapping
    private static readonly Dictionary<string, string> MorphNameMapping = new Dictionary<string, string>()
    {
        // Eyes
        { "Eye_CloseA", "まばたき" }, // Blink
        { "Eye_WaraiA", "笑い" },     // Smile
        { "Eye_HalfA", "じと目" },    // Half-closed
        { "Eye_OdorokiA", "びっくり" }, // Surprised
        { "Eye_KomariA", "困る" },      // Troubled
        { "Eye_IkariA", "怒り" },       // Angry

        // Mouth - Vowels
        { "Mouth_TalkA_A_L", "あ" },
        { "Mouth_TalkA_I_L", "い" },
        { "Mouth_TalkA_U_L", "う" },
        { "Mouth_TalkA_E_L", "え" },
        { "Mouth_TalkA_O_L", "お" },
        
        { "Mouth_TalkA_A_S", "あ2" }, // Smaller versions?
        { "Mouth_TalkA_I_S", "い2" },
        { "Mouth_TalkA_U_S", "う2" },
        { "Mouth_TalkA_E_S", "え2" },
        { "Mouth_TalkA_O_S", "お2" },

        // Mouth - Expressions
        { "Mouth_WaraiA", "笑い" },
        { "Mouth_IkariA", "怒り" },
        { "Mouth_KomariA", "困る" },
        { "Mouth_UreiA", "▲" }, // Triangle mouth?
        { "Mouth_OdorokiA", "□" }, // Box mouth?
    };

    private static Part[] ReadPartMaterials(List<Renderer> renderers, RawMMDModel model)
    {
        List<Part> parts = new List<Part>();
        int baseShift = 0;

        foreach (Renderer renderer in renderers)
        {
            Mesh mesh;
            if (renderer is MeshRenderer mr)
            {
                var meshfilter = mr.GetComponent<MeshFilter>();
                mesh = meshfilter.mesh;
            }
            else
            {
                mesh = ((SkinnedMeshRenderer)renderer).sharedMesh;
            }
            if (!mesh.isReadable)
            {
                continue;
            }
            var materials = new List<Material>(renderer.sharedMaterials);
            for (int i = 0; i < mesh.subMeshCount; i++)
            {
                var material = (i < materials.Count ? materials[i] : materials[materials.Count - 1]);
                var part = new Part();
                var mat = new MMDMaterial();
                part.Material = mat;
                mat.Name = mat.NameEn = material.name.Replace(" (Instance)","");
                mat.DiffuseColor = Color.white;
                mat.SpecularColor = Color.clear;
                mat.AmbientColor = Color.white * 0.5f;
                mat.Shiness = 5;
                mat.CastSelfShadow = true;
                mat.DrawGroundShadow = true;
                mat.DrawSelfShadow = true;
                mat.EdgeColor = Color.black;
                mat.EdgeSize = 0.4f;
                if (material.HasProperty("_MainTex"))
                {
                    var tex = model.TextureList.Find(t => t.TexturePath.Contains($"/{material.mainTexture.name}.png"));
                    mat.Texture = (tex ?? model.TextureList[0]);
                }
                else
                {
                    mat.Texture = model.TextureList[0];
                }
                mat.MetaInfo = "";
                part.BaseShift = baseShift + mesh.GetSubMesh(i).indexStart;
                part.TriangleIndexNum = mesh.GetSubMesh(i).indexCount;
                parts.Add(part);
            }
            baseShift += mesh.triangles.Length;
        }
        return parts.ToArray();
    }

    private static Vertex[] ReadVerticesAndTriangles(List<Renderer> renderers, Dictionary<Transform, int> boneIndexes, ref List<int> triangleList, Transform root)
    {
        List<Vertex> verticesList = new List<Vertex>();
        int vertexOffset = 0;

        foreach (Renderer renderer in renderers)
        {
            if (renderer is MeshRenderer mr)
            {
                var meshfilter = mr.GetComponent<MeshFilter>();
                //Cache this data to avoid copying arrays.
                var mesh = meshfilter.mesh;
                if (!mesh.isReadable)
                {
                    UmaViewerUI.Instance.ShowMessage($"Mesh {mesh.name} was not readable. Attempting to export", UIMessageType.Warning);
                    try
                    {
                        mesh = MakeReadableMeshCopy(mesh);
                    }
                    catch
                    {
                        UmaViewerUI.Instance.ShowMessage($"Export {mesh.name} Failed : Mesh is not readable", UIMessageType.Error);
                        continue;
                    }
                }
                var vertices = mesh.vertices;
                var normals = mesh.normals;
                var uv = mesh.uv;
                var uv1 = mesh.uv2;
                var uv2 = mesh.uv3;
                var colors = mesh.colors;
                var triangles = mesh.triangles;

                for (int i = 0; i < vertices.Length; i++)
                {
                    Vertex vertex = new Vertex();
                    vertex.Coordinate = renderer.transform.TransformPoint(vertices[i]);
                    vertex.Normal = normals[i];
                    vertex.UvCoordinate = new Vector2(uv[i].x, 1 - uv[i].y);

                    vertex.ExtraUvCoordinate = new Vector4[3]
                    {
                        uv1.Length > 0 ? new Vector2(uv1[i].x, 1 - uv1[i].y) : Vector2.zero,
                        uv2.Length > 0 ? new Vector2(uv2[i].x, 1 - uv2[i].y) : Vector2.zero,
                        colors.Length > 0 ? colors[i] : Color.clear
                    };

                    vertex.SkinningOperator = new SkinningOperator() { Type = SkinningType.SkinningBdef1 };
                    vertex.SkinningOperator.Param = new Bdef1() { BoneId = GetBoneIndex(boneIndexes, renderer.transform) };
                    vertex.EdgeScale = 1;
                    verticesList.Add(vertex);
                }


                foreach (var triangle in mesh.triangles)
                {
                    triangleList.Add(triangle + vertexOffset);
                }
                vertexOffset += vertices.Length;
            }
            else if (renderer is SkinnedMeshRenderer smr)
            {
                var mesh = smr.sharedMesh;
                if (!mesh.isReadable)
                {
                    UmaViewerUI.Instance.ShowMessage($"Mesh {mesh.name} was not readable. Attempting to export", UIMessageType.Warning);
                    try
                    {
                        mesh = MakeReadableMeshCopy(mesh);
                    }
                    catch
                    {
                        UmaViewerUI.Instance.ShowMessage($"Export {mesh.name} Failed : Mesh is not readable", UIMessageType.Error);
                        continue;
                    }
                }
                var vertices = mesh.vertices;
                var normals = mesh.normals;
                var uv = mesh.uv;
                var uv1 = mesh.uv2;
                var uv2 = mesh.uv3;
                var colors = mesh.colors;
                var boneCounts = mesh.GetBonesPerVertex();
                var skinbone = smr.bones;
                var skinbones = smr.bones;
                var weights = mesh.boneWeights;
                var bakemesh = new Mesh();
                smr.BakeMesh(bakemesh,true);

                for (int i = 0; i < vertices.Length; i++)
                {
                    Vertex vertex = new Vertex();
                    vertex.Coordinate = root.InverseTransformPoint(smr.transform.TransformPoint(bakemesh.vertices[i])); 
                    vertex.Normal = normals[i];
                    vertex.UvCoordinate = new Vector2(uv[i].x, 1 - uv[i].y);
                    vertex.ExtraUvCoordinate = new Vector4[3]
                    {
                        uv1.Length > 0 ? new Vector2(uv1[i].x, 1 - uv1[i].y) : Vector2.zero,
                        uv2.Length > 0 ? new Vector2(uv2[i].x, 1 - uv2[i].y) : Vector2.zero,
                        colors.Length > 0 ? colors[i] : Color.clear
                    };

                    var boneWeight = weights[i];
                    var boneCount = boneCounts[i];

                    switch (boneCount)
                    {
                        case 0:
                            vertex.SkinningOperator = new SkinningOperator() { Type = SkinningType.SkinningBdef1 };
                            vertex.SkinningOperator.Param = new Bdef1() { BoneId = GetBoneIndex(boneIndexes, renderer.transform) };
                            break;

                        default:
                        case 1:
                            vertex.SkinningOperator = new SkinningOperator() { Type = SkinningType.SkinningBdef1 };
                            vertex.SkinningOperator.Param = new Bdef1() { BoneId = GetBoneIndex(boneIndexes, skinbone[boneWeight.boneIndex0]) };
                            break;

                        case 2:
                            vertex.SkinningOperator = new SkinningOperator() { Type = SkinningType.SkinningBdef2 };
                            vertex.SkinningOperator.Param = new Bdef2()
                            {
                                BoneId = new int[]{
                                    GetBoneIndex(boneIndexes, skinbone[boneWeight.boneIndex0]),
                                    GetBoneIndex(boneIndexes, skinbone[boneWeight.boneIndex1]),
                                },
                                BoneWeight = boneWeight.weight0
                            };
                            break;

                        case 3:
                        case 4:
                            vertex.SkinningOperator = new SkinningOperator() { Type = SkinningType.SkinningBdef4 };
                            vertex.SkinningOperator.Param = new Bdef4()
                            {
                                BoneId = new int[]{
                                    GetBoneIndex(boneIndexes, skinbone[boneWeight.boneIndex0]),
                                    GetBoneIndex(boneIndexes, skinbone[boneWeight.boneIndex1]),
                                    GetBoneIndex(boneIndexes, skinbone[boneWeight.boneIndex2]),
                                    GetBoneIndex(boneIndexes, skinbone[boneWeight.boneIndex3]),
                                },
                                BoneWeight = new float[]
                                {
                                    boneWeight.weight0,
                                    boneWeight.weight1,
                                    boneWeight.weight2,
                                    boneWeight.weight3
                                }
                            };
                            break;
                    }
                    vertex.EdgeScale = 1;
                    verticesList.Add(vertex);
                }

                foreach (var triangle in mesh.triangles)
                {
                    triangleList.Add(triangle + vertexOffset);
                }
                vertexOffset += vertices.Length;
            }
        }
        return verticesList.ToArray();
    }

    private static int GetBoneIndex(Dictionary<Transform, int> boneIndexes, Transform bone)
    {
        // 被过滤骨的权重转交给最近的有效祖先，保证索引始终指向实际 PMX 骨骼。
        Transform current = bone;
        while (current != null)
        {
            if (boneIndexes.TryGetValue(current, out int index))
            {
                return index;
            }
            current = current.parent;
        }

        // 兜底到「全ての親」。
        return 0;
    }

    /// <summary> Credit to pohype: https://discussions.unity.com/t/reading-meshes-at-runtime-that-are-not-enabled-for-read-write/804189/7 </summary>
    public static Mesh MakeReadableMeshCopy(Mesh nonReadableMesh)
    {
        Mesh meshCopy = new Mesh();
        meshCopy.indexFormat = nonReadableMesh.indexFormat;

        // Handle vertices
        GraphicsBuffer verticesBuffer = nonReadableMesh.GetVertexBuffer(0);
        int totalSize = verticesBuffer.stride * verticesBuffer.count;
        byte[] data = new byte[totalSize];
        verticesBuffer.GetData(data);
        meshCopy.SetVertexBufferParams(nonReadableMesh.vertexCount, nonReadableMesh.GetVertexAttributes());
        meshCopy.SetVertexBufferData(data, 0, 0, totalSize);
        verticesBuffer.Release();

        // Handle triangles
        meshCopy.subMeshCount = nonReadableMesh.subMeshCount;
        GraphicsBuffer indexesBuffer = nonReadableMesh.GetIndexBuffer();
        int tot = indexesBuffer.stride * indexesBuffer.count;
        byte[] indexesData = new byte[tot];
        indexesBuffer.GetData(indexesData);
        meshCopy.SetIndexBufferParams(indexesBuffer.count, nonReadableMesh.indexFormat);
        meshCopy.SetIndexBufferData(indexesData, 0, 0, tot);
        indexesBuffer.Release();

        // Restore submesh structure
        uint currentIndexOffset = 0;
        for (int i = 0; i < meshCopy.subMeshCount; i++)
        {
            uint subMeshIndexCount = nonReadableMesh.GetIndexCount(i);
            meshCopy.SetSubMesh(i, new SubMeshDescriptor((int)currentIndexOffset, (int)subMeshIndexCount));
            currentIndexOffset += subMeshIndexCount;
        }

        // Recalculate normals and bounds
        meshCopy.RecalculateNormals();
        meshCopy.RecalculateBounds();

        return meshCopy;
    }
}
